---
title: "UCD GW Observatory"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    
---

```{r setup, include=FALSE}
library(dygraphs)
library(quantmod)
library(flexdashboard)
library(leaflet)

getSymbols(c("MSFT", "HPQ", "INTC"), from = "2019-01-01", auto.assign=TRUE)
```


Groundwater Levels
===================================== 


### Well 1

```{r}
dygraph(MSFT[,2:4], group = "stocks") %>% 
  dySeries(c("MSFT.Low", "MSFT.Close", "MSFT.High"), label = "MW1")
```

### Well 2

```{r}
dygraph(HPQ[,2:4], group = "stocks") %>% 
  dySeries(c("HPQ.Low", "HPQ.Close", "HPQ.High"), label = "MW2")
```

### Well 3

```{r}
dygraph(INTC[,2:4], group = "stocks") %>% 
  dySeries(c("INTC.Low", "INTC.Close", "INTC.High"), label = "MW3")
```


Battery Life
===================================== 


```{r}
ids <- paste0("MW ", 1:3)
lng <- c(174.768, 174.668, 174.3)
lat <- c(-36.852, -36.5, -36.6)
bat <- c(82, 52, 62)

wells <- data.frame(ids, lng, lat, bat)

leaflet() %>%
  addProviderTiles(providers$Esri.WorldImagery) %>%  
  addMarkers(lng=lng, 
             lat=lat, 
             popup=paste0(ids, " <br> ", "Battery: ", bat, "%")) %>% 
  setView(mean(lng), mean(lat), zoom = 9)
```


About
===================================== 

### This is where we include some markdown document about:  

* the great work we're doing  
* how to use the site  
* contact information if anything looks funny  
* etc  