@echo off
del *.#umcmc*
del *._mcmc*
del HO1._*
del HO1.#*
del HO1-forward._*
del HO1-forward.#*
del HOmodel_forward\HO._obsout
del HOmodel_forward\HO.lst
del HOmodel_forward\HO.pvl
del HOmodel_prediction\HO._obsout
del HOmodel_prediction\HO.lst
del HOmodel_prediction\HO.pvl